from __future__ import annotations

import html
from pathlib import Path

from app.artifacts.chart_generator import build_chart_payload, generate_chart_svg
from app.schemas.chat import ChartData, TableData


def generate_dashboard(path: Path, *, title: str, table: TableData, chart: ChartData | None, answer: str | None = None) -> dict:
    chart_path = path.with_suffix(".svg")
    chart_payload = generate_chart_svg(chart_path, title=title, table=table, chart=chart)
    rows = table.rows[:25]
    headers = "".join(f"<th>{html.escape(str(column))}</th>" for column in table.columns)
    body = "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(value if value is not None else ''))}</td>" for value in row) + "</tr>"
        for row in rows
    )
    chart_svg = chart_path.read_text(encoding="utf-8")
    html_text = f"""<!doctype html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\" />
<title>{html.escape(title)}</title>
<style>
body {{ margin: 0; font-family: Aptos, Arial, sans-serif; background: #f8fafc; color: #003323; }}
.shell {{ max-width: 1180px; margin: 32px auto; padding: 0 20px; }}
.card {{ background: #fffdee; border: 1px solid rgba(0,51,35,.14); border-radius: 24px; box-shadow: 0 24px 80px rgba(15,23,42,.12); padding: 24px; margin-bottom: 20px; }}
h1 {{ margin: 0 0 8px; font-size: 30px; }}
.kpis {{ display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; margin: 18px 0; }}
.kpi {{ border-radius: 18px; background: linear-gradient(135deg, #003323, #4169e1); color: #fffdee; padding: 18px; }}
.kpi span {{ display: block; opacity: .8; font-size: 12px; text-transform: uppercase; letter-spacing: .12em; }}
.kpi strong {{ display: block; margin-top: 8px; font-size: 24px; }}
table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
th {{ background: #003323; color: #fffdee; text-align: left; padding: 10px; }}
td {{ border-bottom: 1px solid #dbe7e1; padding: 9px 10px; }}
</style>
</head>
<body>
<div class=\"shell\">
<section class=\"card\"><h1>{html.escape(title)}</h1><p>{html.escape(answer or 'Generated by NeuralSwitch from verified RAPID/chat result data.')}</p>
<div class=\"kpis\"><div class=\"kpi\"><span>Rows</span><strong>{len(table.rows):,}</strong></div><div class=\"kpi\"><span>Columns</span><strong>{len(table.columns):,}</strong></div><div class=\"kpi\"><span>Chart</span><strong>{html.escape(str(chart.type if chart else 'table'))}</strong></div></div></section>
<section class=\"card\">{chart_svg}</section>
<section class=\"card\"><h2>Data Preview</h2><table><thead><tr>{headers}</tr></thead><tbody>{body}</tbody></table></section>
</div>
</body>
</html>"""
    path.write_text(html_text, encoding="utf-8")
    return chart_payload
